### ISSUE TITLE
开发模式启动服务器时，cpu占用率一直100%，这是个怎么回事？

### ISSUE THREAD

**Issue by dunmengjun** [wssgcg1213/koa2-react-isomorphic-boilerplate#10]
如题，我在windows上启动的，cpu占用率一直100%，程序能正常运行

**Comment by wssgcg1213** [comment]
不好意思，我还没有在win下使用过，晚点我看看

**Comment by dunmengjun** [comment]
嗯，好的，，node服务进程的cpu占用率一直是70%--80%，没有访问就空挂着也一样，这是不科学的，期待修复这个bug

**Comment by wssgcg1213** [comment]
我测试了一下 没有这个问题 cpu几乎是0

我测试的环境是 win7 + node-v4.4.5 LTS

你能提供一下你的环境么

**Comment by wssgcg1213** [comment]
@dunmengjun  
我确认了一下 
在 macOS 下面我的CPU占用有到 70%  因为多核心的原因所以完全没有卡的感觉
CPU占用过高我怀疑跟文件监视有关, 我使用了一个叫 chokidar 的模块来处理这件事情, 可能还需要做一下针对性的优化.

我在下个版本做这件事情吧

**Comment by dunmengjun** [comment]
我的环境是node v4.4.4 LTS   npm 3.9.0   win10     好吧，嗯，期待你的下一个版本

**Comment by jyanchen** [comment]
@wssgcg1213 我自己也在尝试优化（我的电脑跑是在是太卡了。。。），可是都没什么效果。方便提供一下优化思路吗？

**Comment by wssgcg1213** [comment]
chokidar 的配置可能需要优化，一下子关注了太多文件，磁盘操作耗了一部分性能

**Comment by jyanchen** [comment]
@wssgcg1213 我测试了一下和chokidar没有太大关系，我修改了devMiddleware的参数，如下：
```js
watchOptions: {
    aggregateTimeout: 300,
    poll: false,
    ignored: /node_modules/
  }
```
测试后，空闲时（即不对项目进行任何修改），没有cpu和io消耗。保存编译时，cpu：3%-25%，io：~0.1M，但是内存增加了。

我也试过注释掉所有chokidar的代码，编译时cpu会减少一点，其余不变，多有功能也一切正常。
我想问下chokidar的相关代码是什么意思？

**Comment by wssgcg1213** [comment]
chokidar 是用来监听文件变化的，我回去测试一下吧

**Comment by jyanchen** [comment]
可是我注释掉了，也没有发现有什么异常啊？热更新也能正常使用

**Comment by wssgcg1213** [comment]
那个是给 koa服务端controller 热更新用的，服务端逻辑变化后重新require 对应的js文件

**Comment by wssgcg1213** [comment]
关闭后闲时CPU从50%降至几乎0%，ref: http://webpack.github.io/docs/webpack-dev-middleware.html#watchoptions-aggregatetimeout

**Comment by hscfapps** [comment]
服务器上打包的时候，node的cup占用也都是100%以上，有什么解决方案吗？
